services:
  # vector db
  qdrant:
    image: qdrant/qdrant:latest
    container_name: sift_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: always

  # query engine
  query_engine:
    image: meledo/sift-video-query-engine:latest
    build:
      context: ./services/query_engine
      dockerfile: Dockerfile
    container_name: sift_query_engine
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
      - QDRANT_URL=http://qdrant:6334
      - OUTPUT_DIR=/output
    volumes:
      - ./output:/output
      - ./videos:/videos
      - huggingface_cache:/root/.cache/huggingface
      - ./ui:/app/static
    depends_on:
      - qdrant
  
  # ingestion service
  ingestion:
    image: meledo/sift-video-ingestion:latest
    build:
      context: ./services/ingestion
      dockerfile: Dockerfile
    container_name: sift_ingestion
    restart: always
    volumes:
      - ./videos:/videos
      - ./output:/output
    depends_on:
      - qdrant
  
  # embedding service
  embedding:
    image: meledo/sift-video-embedding:latest
    build:
      context: ./services/embedding
      dockerfile: Dockerfile
    container_name: sift_embedding
    restart: always
    volumes:
      - ./output:/output
      - ./services/embedding/models:/app/models
    depends_on:
      - ingestion

volumes:
  huggingface_cache:
